# Generated by Django 5.0.8 on 2025-07-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('certificate', 'G-TEC Certificate'), ('diploma', 'G-TEC Diploma'), ('master', 'Master Course'), ('special', 'G-TEC Special Program'), ('sap', 'SAP Course')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
